# This is a sample aws-auth-patch.yml file. 
# Actual aws-auth-patch.yml will be created at /System/Volumes/Data/private/tmp/aws-auth-patch.yml path.

apiVersion: v1
data:
  mapRoles: |
   - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::527384365589:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1DBHED9TMYRZZ
      username: system:node:{{EC2PrivateDNSName}}
      - system:masters
      rolearn: arn:aws:iam::527384365589:role/FlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-05-11T11:16:26Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1631"
  uid: 86402a4e-a9ff-4721-8c24-f0c4258f7440


# apiVersion: v1
# data:
#   mapRoles: |
#     - groups:
#       - system:masters
#       rolearn: arn:aws:iam::527384365589:role/FlaskDeployCBKubectlRole
#       username: build 
#     - groups:
#       - system:bootstrappers
#       - system:nodes
#       rolearn: arn:aws:iam::527384365589:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1WXOYKU8YIBAB
#       username: system:node:{{EC2PrivateDNSName}}
# kind: ConfigMap
# metadata:
#   creationTimestamp: "2022-09-19T20:40:23Z"
#   name: aws-auth
#   namespace: kube-system
#   resourceVersion: "1605"
#   uid: 6924a9d5-8e07-4c62-805c-5a0df23bd945
